//
// WebApiProjectError.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import <Foundation/Foundation.h>

@interface WebApiProjectException : NSException

@property(strong)NSURLResponse *response;
@property(strong)NSData *data;
@property(assign)NSInteger statusCode;

+(instancetype)exceptionWithName:(NSString *)name reason:(NSString*)reason response:(NSURLResponse*)res data:(NSData*)dat;

@end

