//
// WebApiProjectManager.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiProjectManager.h"

@implementation WebApiProjectManager

-(WebApiBriologin*)createWebApiBriologin
{
	WebApiBriologin *result = [[WebApiBriologin alloc] initWithManager:self];
	return result;
}

-(NSData*)startReqest:(NSMutableURLRequest*)request withResponse:(NSHTTPURLResponse**)response withError:(NSError**)error
{
	request.timeoutInterval = self.timeout;

	__block NSHTTPURLResponse *res = nil;
	__block NSError *err = nil;
	__block NSData *data = nil;
	__block NSCondition *condition = [[NSCondition alloc] init];
	@try {
		[condition lock];
		NSURLSession *session = [NSURLSession sharedSession];
		NSURLSessionDataTask *task = [session dataTaskWithRequest:request completionHandler:^(NSData *requestData, NSURLResponse *requestResponse, NSError *requestError) {
			data = requestData;
			res = (NSHTTPURLResponse*)requestResponse;
			err = requestError;
	
			[condition lock];
			[condition signal];
			[condition unlock];
		}];
		[task resume];
	
		[condition wait];
		[condition unlock];
	} @catch (NSException *exception) {
	}
	
	if((data == nil) && (res == nil))
		@throw [NSException exceptionWithName:err.domain reason:err.localizedDescription userInfo:err.userInfo];
	if(error != nil)
		*error = err;
	if(response != nil)
		*response = res;
	return data;
}

-(instancetype)init
{
	self = [super init];
	if(self){

	}
	return self;
}

@end
