//
// WebApiBriologin.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiBriologin.h"

@implementation WebApiBriologin

-(void)getWebsocketAuthTokenWithCompletion:(void(^)(NSData* result, WebApiProjectErrorBase *error))completion
{
	NSError *error = nil;
	NSString *partUrl = @"https://pestproridall.briostack.com/api/loginService";
	NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:partUrl]];

	if([self.manager.delegate respondsToSelector:@selector(WebApiProjectManager:willPrepareRequest:)] == YES)
		[self.manager.delegate WebApiProjectManager:self.manager willPrepareRequest:request];

	[request setHTTPMethod:@"POST"];

	[request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];

	if([self.manager.delegate respondsToSelector:@selector(WebApiProjectManager:didPrepareRequest:)] == YES)
		[self.manager.delegate WebApiProjectManager:self.manager didPrepareRequest:request];

	[self.manager startReqest:request withCompletion:^(NSData *result, NSHTTPURLResponse *response, WebApiProjectErrorBase *error) {
		if(error == nil){
			WebApiProjectErrorBase *erroeResult = nil;
			NSError *errorJson = nil;
			NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:result options:0 error:&errorJson];
			if(errorJson != nil){
				erroeResult = [[WebApiProjectErrorBase alloc] init];
				error.error = errorJson;
				completion(nil, erroeResult);
				return;
			}
	NSData *res = WebApiProjectbase64DecodeString(dic[@"{
   "service":"loginService",
   "params":{
      "map":{
         
      }
   },
   security:{
      map:{
        USERNAME: "mmeyer",
        PASSWORD: "password"
      }
   },
   userInfo:false,
   application: api
"]);
			completion(res, error);
		}else completion(nil, error);
	}];
}


@end
