//
// WebApiBriologin.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import <Foundation/Foundation.h>
#import "WebApiProjectCore.h"
@interface WebApiBriologin : WebApiProjectApiBase

-(NSData*)getWebsocketAuthToken;

@end
