//
// WebApiNewData.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import <Foundation/Foundation.h>
#import "WebApiProjectData.h"

@interface WebApiNewData : WebApiProjectData

/*
{
"service":"getProductStores", 
"params":{
 "map":{
}
},
"security":
  { "map":{
"USERNAME":"mmeyer", "PASSWORD":"password"
}
},
userInfo:false,
"application":api
}
*/
@property(strong)NSData* name;

-(NSDictionary*)save;
-(void)load:(NSDictionary*)dic;

-(instancetype)initWithDictionary:(NSDictionary*)dic;

@end
