//
// WebApiNewData.m
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiNewData.h"
#import "WebApiProjectCore.h"

@implementation WebApiNewData

@synthesize name;

-(NSDictionary*)save
{
	NSMutableDictionary *result = [[NSMutableDictionary alloc] init];

	result[@"name"] = WebApiProjectbase64EncodeData(self.name);
	return result;
}

-(void)load:(NSDictionary*)dic
{
	self.name = WebApiProjectbase64DecodeString(dic[@"name"]);
}

-(instancetype)initWithDictionary:(NSDictionary*)dic
{
	self = [self init];
	if(self){
		[self load:dic];
	}
	return self;
}

-(instancetype)init
{
	self = [super init];
	if(self){
	}
	return self;
}

@end
