//
// WebApiProjectError.m
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiProjectError.h"

@implementation WebApiProjectException

@synthesize response;
@synthesize data;
@synthesize statusCode;

-(NSString*)description
{
	return [NSString stringWithFormat:@"%@ %@\n%@", self.name, self.response, [self callStackSymbols]];
}

+(instancetype)exceptionWithName:(NSString *)name reason:(NSString*)reason response:(NSURLResponse*)res data:(NSData*)dat
{
	WebApiProjectException *result = [[WebApiProjectException alloc] initWithName:name reason:reason userInfo:nil];
	result.response = res;
	result.data = dat;
	return result;
}

@end

