//
// WebApiNewData.m
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import "WebApiNewData.h"
#import "WebApiBriostackCore.h"

@implementation WebApiNewData

@synthesize name;

-(NSDictionary*)save
{
	NSMutableDictionary *result = [[NSMutableDictionary alloc] init];

	result[@"name"] = WebApiBriostackbase64EncodeData(self.name);
	return result;
}

-(void)load:(NSDictionary*)dic
{
	self.name = WebApiBriostackbase64DecodeString(dic[@"name"]);
}

-(instancetype)initWithDictionary:(NSDictionary*)dic
{
	self = [self init];
	if(self){
		[self load:dic];
	}
	return self;
}

-(instancetype)init
{
	self = [super init];
	if(self){
	}
	return self;
}

@end
