//
// WebApiNewData.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import <Foundation/Foundation.h>
#import "WebApiBriostackData.h"

@interface WebApiNewData : WebApiBriostackData

@property(strong)NSData* name;

-(NSDictionary*)save;
-(void)load:(NSDictionary*)dic;

-(instancetype)initWithDictionary:(NSDictionary*)dic;

@end
