//
// WebApiProjectData.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import <Foundation/Foundation.h>

@interface WebApiProjectData : NSObject

-(NSDictionary*)save;
-(void)load:(NSDictionary*)dic;

-(NSString*)saveToJSON;
-(void)loadFromJSON:(NSString*)json;

-(instancetype)initWithJSON:(NSString*)json;
-(instancetype)initWithDictionary:(NSDictionary*)dic;

@end
