//
// WebApiProjectError.m
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiProjectError.h"

@implementation WebApiProjectErrorBase

@synthesize response;
@synthesize error;
@synthesize statusCode;

-(id)initWithResponse:(NSURLResponse*)aResponse
{
	self = [super init];
	if(self){
		self.response = aResponse;
		if([aResponse isKindOfClass:[NSHTTPURLResponse class]] == YES)
			self.statusCode = [(NSHTTPURLResponse *)response statusCode];
	}
	return self;
}

@end

