//
// WebApiProjectManager.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiProjectManager.h"

@implementation WebApiProjectManager

-(WebApiBriologin*)createWebApiBriologin
{
	WebApiBriologin *result = [[WebApiBriologin alloc] initWithManager:self];
	return result;
}

-(void)startReqest:(NSMutableURLRequest*)request withCompletion:(void (^)(NSData *result, NSHTTPURLResponse *response, WebApiProjectErrorBase * error))completion
{
	request.timeoutInterval = self.timeout;

	NSURLSession *session = [NSURLSession sharedSession];
	NSURLSessionDataTask *task = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
		WebApiProjectErrorBase *errorApi = nil;
		if(error != nil){
			errorApi = [[WebApiProjectErrorBase alloc] initWithResponse:response];
			errorApi.error = error;
		}
		completion(data, (NSHTTPURLResponse*)response, errorApi);
	}];
	[task resume];
}

-(instancetype)init
{
	self = [super init];
	if(self){

	}
	return self;
}

@end
