//
// WebApiBriologin.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import <Foundation/Foundation.h>
#import "WebApiProjectCore.h"
/*
{
   "service":"loginService",
   "params":{
      "map":{
         
      }
   },
   security:{
      map:{
        USERNAME: "mmeyer",
        PASSWORD: "password"
      }
   },
   userInfo:false,
   application: api
} 
*/
@interface WebApiBriologin : WebApiProjectApiBase

-(void)getWebsocketAuthTokenWithCompletion:(void(^)(NSData* result, WebApiProjectErrorBase *error))completion;
-(void)name2WithCompletion:(void(^)(WebApiProjectErrorBase *error))completion;

@end
