//
// WebApiProjectError.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import <Foundation/Foundation.h>

@interface WebApiProjectErrorBase : NSObject

@property(strong)NSURLResponse *response;
@property(strong)NSError *error;
@property(assign)NSInteger statusCode;

-(id)initWithResponse:(NSURLResponse*)aResponse;

@end

