//
// WebApiProjectManager.h
// Project 1.0
//
// Generated by ApiGenerator on Tuesday, November 21, 2023
//

#import "WebApiProjectCore.h"
#import "WebApiBriologin.h"

@interface WebApiProjectManager : WebApiProjectManagerCore

-(WebApiBriologin*)createWebApiBriologin;

@end
