//
// WebApiBriostackManager.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import "WebApiBriostackCore.h"
#import "WebApiNewApi.h"
#import "WebApiNewApi2.h"

@interface WebApiBriostackManager : WebApiBriostackManagerCore

@property(strong)NSString* authorizationName;
@property(strong)NSString* authorizationPassword;

-(void)useAuthorizationName:(NSString*)name withPassword:(NSString*)password;

-(WebApiNewApi*)createWebApiNewApi;
-(WebApiNewApi2*)createWebApiNewApi2;

@end
