//
// WebApiBriostackData.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import <Foundation/Foundation.h>

@interface WebApiBriostackData : NSObject

-(NSDictionary*)save;
-(void)load:(NSDictionary*)dic;

-(NSString*)saveToJSON;
-(void)loadFromJSON:(NSString*)json;

-(instancetype)initWithJSON:(NSString*)json;
-(instancetype)initWithDictionary:(NSDictionary*)dic;

@end
