//
// WebApiBriostackError.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import <Foundation/Foundation.h>

@interface WebApiBriostackErrorBase : NSObject

@property(strong)NSURLResponse *response;
@property(strong)NSError *error;
@property(assign)NSInteger statusCode;

-(id)initWithResponse:(NSURLResponse*)aResponse;

@end

