//
// WebApiNewApi.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import <Foundation/Foundation.h>
#import "WebApiBriostackCore.h"
#import "WebApiNewData.h"

@interface WebApiNewApi : WebApiBriostackApiBase

-(void)loginServiceWithCompletion:(void(^)(NSData* result, WebApiBriostackErrorBase *error))completion;
-(void)logOutWithLogOut:(NSDate*)logOut withCompletion:(void(^)(NSData* result, WebApiBriostackErrorBase *error))completion;
-(void)ErrorsWithCompletion:(void(^)(WebApiBriostackErrorBase *error))completion;
-(void)getActiveWorkareasWithGetActiveWorkArea:(WebApiNewData*)getActiveWorkArea withCompletion:(void(^)(NSData* result, WebApiBriostackErrorBase *error))completion;
-(void)getAutoPayReportWithGetAutoPayReport:(WebApiNewData*)getAutoPayReport withCompletion:(void(^)(NSData* result, WebApiBriostackErrorBase *error))completion;

@end
