//
// WebApiBriostackManager.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, April 17, 2024
//

#import "WebApiBriostackCore.h"
#import "WebApiNewApi.h"
#import "WebApiNewApi2.h"

@interface WebApiBriostackManager : WebApiBriostackManagerCore

-(WebApiNewApi*)createWebApiNewApi;
-(WebApiNewApi2*)createWebApiNewApi2;

@end
