//
// WebApiBriostackManager.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, April 17, 2024
//

#import "WebApiBriostackManager.h"

@implementation WebApiBriostackManager

-(WebApiNewApi*)createWebApiNewApi
{
	WebApiNewApi *result = [[WebApiNewApi alloc] initWithManager:self];
	return result;
}
-(WebApiNewApi2*)createWebApiNewApi2
{
	WebApiNewApi2 *result = [[WebApiNewApi2 alloc] initWithManager:self];
	return result;
}

-(void)startReqest:(NSMutableURLRequest*)request withCompletion:(void (^)(NSData *result, NSHTTPURLResponse *response, WebApiBriostackErrorBase * error))completion
{
	request.timeoutInterval = self.timeout;

	NSURLSession *session = [NSURLSession sharedSession];
	NSURLSessionDataTask *task = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
		WebApiBriostackErrorBase *errorApi = nil;
		if(error != nil){
			errorApi = [[WebApiBriostackErrorBase alloc] initWithResponse:response];
			errorApi.error = error;
		}
		completion(data, (NSHTTPURLResponse*)response, errorApi);
	}];
	[task resume];
}

-(instancetype)init
{
	self = [super init];
	if(self){

	}
	return self;
}

@end
