//
// WebApiBriostackData.m
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, April 17, 2024
//

#import "WebApiBriostackData.h"

@implementation WebApiBriostackData

-(NSDictionary*)save
{
	@throw [NSException exceptionWithName:NSInternalInconsistencyException reason:[NSString stringWithFormat:@"You must override %@ in a subclass", NSStringFromSelector(_cmd)] userInfo:nil];
}

-(void)load:(NSDictionary*)dic
{
	@throw [NSException exceptionWithName:NSInternalInconsistencyException reason:[NSString stringWithFormat:@"You must override %@ in a subclass", NSStringFromSelector(_cmd)] userInfo:nil];
}

-(NSString*)saveToJSON
{
	NSError *error = nil;
	NSData *data = [NSJSONSerialization dataWithJSONObject:[self save] options:0 error:&error];
	if(error != nil)
		@throw [NSException exceptionWithName:NSInvalidArgumentException reason:error.description userInfo:error.userInfo];
	return [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
}

-(void)loadFromJSON:(NSString*)json
{
	NSError *error = nil;
	NSDictionary *dic = [NSJSONSerialization JSONObjectWithData:[json dataUsingEncoding:NSUTF8StringEncoding] options:0 error:&error];
	if(error != nil)
		@throw [NSException exceptionWithName:NSInvalidArgumentException reason:error.description userInfo:error.userInfo];
	[self load:dic];
}

-(instancetype)initWithDictionary:(NSDictionary*)dic
{
	self = [super init];
	if(self){
		[self load:dic];
}
	return self;
}

-(instancetype)initWithJSON:(NSString*)json
{
	self = [super init];
	if(self){
		[self loadFromJSON:json];
	}
	return self;
}

@end
