//
// WebApiNewApi2.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, March 13, 2024
//

#import <Foundation/Foundation.h>
#import "WebApiBriostackCore.h"
@interface WebApiNewApi2 : WebApiBriostackApiBase


@end
