//
// WebApiBriostackError.m
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, April 17, 2024
//

#import "WebApiBriostackError.h"

@implementation WebApiBriostackErrorBase

@synthesize response;
@synthesize error;
@synthesize statusCode;

-(id)initWithResponse:(NSURLResponse*)aResponse
{
	self = [super init];
	if(self){
		self.response = aResponse;
		if([aResponse isKindOfClass:[NSHTTPURLResponse class]] == YES)
			self.statusCode = [(NSHTTPURLResponse *)response statusCode];
	}
	return self;
}

@end

