//
// WebApiBriostackCore.h
// Briostack 1.0
//
// Generated by ApiGenerator on Wednesday, April 17, 2024
//

#import <Foundation/Foundation.h>
#import "WebApiBriostackError.h"

@class WebApiBriostackManagerCore;

@protocol WebApiBriostackManagerDelegate <NSObject>

@optional
-(void)WebApiBriostackManager:(WebApiBriostackManagerCore*)manager didPrepareRequest:(NSMutableURLRequest*)request;
-(void)WebApiBriostackManager:(WebApiBriostackManagerCore*)manager willPrepareRequest:(NSMutableURLRequest*)request;
-(void)WebApiBriostackManager:(WebApiBriostackManagerCore*)manager prepareJSONContent:(NSObject*)object withRequest:(NSMutableURLRequest*)request;

@end

@interface WebApiBriostackManagerCore: NSObject{
	NSString *_baseURL;
}

@property(weak)id<WebApiBriostackManagerDelegate> delegate;
@property(strong)NSString *baseURL;
@property(assign)int timeout;

@property(strong)NSData* globalVariable;

-(void)startReqest:(NSMutableURLRequest*)request withCompletion:(void (^)(NSData *result, NSHTTPURLResponse *response, WebApiBriostackErrorBase * error))completion;

-(void)removeCookies;

@end

@interface WebApiBriostackApiBase : NSObject

@property(weak)WebApiBriostackManagerCore *manager;

-(instancetype)initWithManager:(WebApiBriostackManagerCore*)apiManager;

@end

extern NSString* WebApiBriostackObjectToJson(id object);
extern NSDictionary* WebApiBriostackPostToDictionary(NSString *value);
extern NSString* WebApiBriostackDictionaryToPost(NSDictionary *value, NSString *name);
extern NSString* WebApiBriostackArrayToPost(NSArray *value, NSString *name);
extern NSString* WebApiBriostackObjectToPost(NSObject *value, NSString *name);
extern void WebApiBriostackDictionaryToPostDataValue(NSObject *value, NSString *name, NSMutableData *content);
extern void WebApiBriostackDictionaryToPostData(NSDictionary *value, NSString *name, NSMutableData *content);
extern void WebApiBriostackArrayToPostData(NSArray *value, NSString *name, NSMutableData *content);
extern void WebApiBriostackObjectToPostData(NSObject *value, NSString *name, NSMutableData *content);

extern NSString* WebApiBriostackbase64EncodeData(NSData *objData);
extern NSData* WebApiBriostackbase64DecodeString(NSString *strBase64);
extern NSString* WebApiBriostackbase64EncodeString(NSString *strData);
